"""Persistent day-ahead bid bank for lower-controller training.

Each training date is solved once by the configured upper bidder. The frozen bid, its
activation scenario set, and its arrival context are stored together so lower
MARL training never has to solve the upper problem inside an episode.
"""

from __future__ import annotations

from datetime import datetime
import json
from pathlib import Path
import pickle
import re
from typing import Callable, Iterable

import numpy as np


BID_BANK_VERSION = 1


def _safe_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value)).strip("._")
    return name or "unknown_day"


def _json_default(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (set, tuple)):
        return list(value)
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def _write_json_atomic(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    with temp_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2, default=_json_default)
    temp_path.replace(path)


def save_fixed_bid(path: str | Path, fixed_bid: dict) -> Path:
    """Atomically persist one trusted, locally generated fixed-bid payload."""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    with temp_path.open("wb") as f:
        pickle.dump(fixed_bid, f, protocol=pickle.HIGHEST_PROTOCOL)
    temp_path.replace(path)
    return path


def load_fixed_bid(path: str | Path) -> dict:
    """Load a fixed bid generated by :func:`save_fixed_bid`."""

    with Path(path).open("rb") as f:
        payload = pickle.load(f)
    if not isinstance(payload, dict) or "baseline_plan" not in payload:
        raise ValueError(f"invalid fixed-bid payload: {path}")
    return payload


IDLE_BASELINE_KW = 0.0


def zero_idle_baseline(fixed_bid: dict) -> int:
    """Set the baseline to IDLE_BASELINE_KW in every block that carries no bid.

    A block without submitted or awarded width carries no obligation, and the
    bid LP leaves its baseline unconstrained, so the solver returns whatever
    bound it stopped at. The tracking target there is already zero; the value
    only reaches the lower controller through the bid-lookahead observation,
    whose cached series is dropped here so it is rebuilt from the new baseline.
    Returns the number of blocks changed.
    """

    from dataclasses import is_dataclass, replace

    from market.bid_participation import participation_by_block

    baseline = np.asarray(fixed_bid["baseline_plan"], dtype=float).copy()
    live = participation_by_block(fixed_bid["up_plan"], fixed_bid["down_plan"])
    if "submitted_up_plan" in fixed_bid and "submitted_down_plan" in fixed_bid:
        live |= participation_by_block(
            fixed_bid["submitted_up_plan"], fixed_bid["submitted_down_plan"]
        )
    idle = ~live[: baseline.size]
    changed = int(np.count_nonzero(baseline[idle] != IDLE_BASELINE_KW))
    baseline[idle] = IDLE_BASELINE_KW
    fixed_bid["baseline_plan"] = baseline
    fixed_bid["idle_baseline_kw"] = IDLE_BASELINE_KW
    fixed_bid.pop("_runtime_market_context_cache", None)
    result = fixed_bid.get("result")
    if is_dataclass(result) and hasattr(result, "mean_baseline_kw"):
        fixed_bid["result"] = replace(result, mean_baseline_kw=float(np.mean(baseline)))
    return changed


def forecast_seed_for_day(base_seed: int, day_index: int) -> int:
    """Use independent but reproducible upper-forecast draws for each day."""

    return int(base_seed) + int(day_index) * 1009


def manifest_settings_match(
    manifest: dict, required_settings: dict, *, ignored_keys=()
) -> bool:
    """Return whether every required setting is present and unchanged."""

    actual = manifest.get("settings") or {}
    if not isinstance(actual, dict):
        return False
    ignored = {str(key) for key in ignored_keys}
    for key, expected in required_settings.items():
        if key in ignored:
            continue
        if key not in actual or actual[key] != expected:
            return False
    return True


def _entry_summary(info: dict) -> dict:
    keys = (
        "service_date",
        "forecast_seed",
        "method",
        "activation_mode",
        "activation_scenarios",
        "bid_status",
        "bid_solved",
        "bid_feasible",
        "bid_objective_capacity_kw_block",
        "submitted_mean_up_kw",
        "submitted_mean_down_kw",
        "submitted_participating_blocks",
        "awarded_mean_up_kw",
        "awarded_mean_down_kw",
        "bid_mean_baseline_kw",
        "bid_mean_up_kw",
        "bid_mean_down_kw",
        "bid_max_up_kw",
        "bid_max_down_kw",
        "bid_participating_blocks",
        "bid_global_tracking_rate",
        "target_min_kw",
        "target_max_kw",
    )
    return {key: info.get(key) for key in keys}


def build_training_bid_bank(
    payloads: Iterable[dict],
    output_dir: str | Path,
    *,
    base_forecast_seed: int,
    build_fixed_bid: Callable,
    build_episode: Callable,
    arrival_sampler,
    set_progress_log: Callable,
    artifact_writer: Callable | None = None,
    settings: dict | None = None,
    overwrite: bool = False,
    manifest_name: str = "manifest.json",
) -> dict:
    """Build or resume a persistent upper-bid bank.

    A manifest and one entry JSON are written after every successful date, so a
    long multi-day solve can resume without repeating completed bid solves.
    """

    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    payloads = list(payloads)
    manifest_path = output_dir / str(manifest_name)
    created_at = datetime.now().isoformat(timespec="seconds")
    if manifest_path.exists() and not overwrite:
        try:
            previous = json.loads(manifest_path.read_text(encoding="utf-8"))
            created_at = str(previous.get("created_at") or created_at)
        except (OSError, ValueError, TypeError):
            pass

    entries: list[dict] = []
    failures: list[dict] = []

    def write_manifest() -> None:
        manifest = {
            "version": BID_BANK_VERSION,
            "created_at": created_at,
            "updated_at": datetime.now().isoformat(timespec="seconds"),
            "complete": len(entries) == len(payloads) and not failures,
            "expected_days": len(payloads),
            "completed_days": len(entries),
            "base_forecast_seed": int(base_forecast_seed),
            "settings": dict(settings or {}),
            "entries": entries,
            "failures": failures,
        }
        _write_json_atomic(manifest_path, manifest)

    for payload_index, payload in enumerate(payloads):
        day_index = int(payload.get("_bid_bank_index", payload_index))
        service_date = str(payload.get("date") or f"train_idx{day_index}")
        day_seed = forecast_seed_for_day(base_forecast_seed, day_index)
        day_dir = output_dir / "days" / f"{day_index:03d}_{_safe_name(service_date)}"
        bid_path = day_dir / "fixed_bid.pkl"
        entry_path = day_dir / "entry.json"

        if not overwrite and bid_path.exists() and entry_path.exists():
            try:
                entry = json.loads(entry_path.read_text(encoding="utf-8"))
                if str(entry.get("service_date")) == service_date:
                    entries.append(entry)
                    print(
                        f"[bid-bank] reuse index={day_index} day={service_date}",
                        flush=True,
                    )
                    write_manifest()
                    continue
            except (OSError, ValueError, TypeError):
                pass

        try:
            series = np.asarray(payload.get("series"), dtype=np.float32).reshape(-1)
            scenario = arrival_sampler.scenario_for_day(service_date)
            progress_path = day_dir / "upper_bid_progress.log"
            set_progress_log(progress_path, reset=True)
            print(
                f"[bid-bank] solve index={day_index} "
                f"day={service_date} seed={day_seed}",
                flush=True,
            )
            fixed_bid = build_fixed_bid(
                series,
                service_date,
                arrival_scenario=scenario,
                forecast_seed=day_seed,
            )
            zero_idle_baseline(fixed_bid)
            fixed_bid["upper_bid_progress_log"] = str(progress_path)
            _target, _tol, _arrival, info = build_episode(fixed_bid, 0)
            save_fixed_bid(bid_path, fixed_bid)
            if artifact_writer is not None:
                artifact_writer(day_dir, fixed_bid, info)

            entry = {
                "index": int(day_index),
                "service_date": service_date,
                "forecast_seed": int(day_seed),
                "source_path": str(payload.get("path") or ""),
                "bid_path": str(bid_path.relative_to(output_dir)),
                "artifact_dir": str((day_dir / "results").relative_to(output_dir)),
                "summary": _entry_summary(info),
            }
            _write_json_atomic(entry_path, entry)
            entries.append(entry)
            write_manifest()
        except Exception as exc:
            failure = {
                "index": int(day_index),
                "service_date": service_date,
                "forecast_seed": int(day_seed),
                "error": f"{type(exc).__name__}: {exc}",
            }
            failures.append(failure)
            write_manifest()
            raise

    write_manifest()
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def merge_training_bid_bank(
    output_dir: str | Path,
    *,
    expected_days: int,
    base_forecast_seed: int,
    settings: dict | None = None,
) -> dict:
    """Merge independently solved day entries into the canonical manifest."""

    output_dir = Path(output_dir).resolve()
    entries = []
    for entry_path in output_dir.glob("days/*/entry.json"):
        try:
            entry = json.loads(entry_path.read_text(encoding="utf-8"))
            bid_path = output_dir / str(entry["bid_path"])
            if bid_path.exists():
                entries.append(entry)
        except (OSError, ValueError, TypeError, KeyError):
            continue
    entries.sort(key=lambda entry: int(entry["index"]))
    duplicate_indices = len({int(entry["index"]) for entry in entries}) != len(entries)
    complete = len(entries) == int(expected_days) and not duplicate_indices
    now = datetime.now().isoformat(timespec="seconds")
    manifest = {
        "version": BID_BANK_VERSION,
        "created_at": now,
        "updated_at": now,
        "complete": complete,
        "expected_days": int(expected_days),
        "completed_days": len(entries),
        "base_forecast_seed": int(base_forecast_seed),
        "settings": dict(settings or {}),
        "entries": entries,
        "failures": [],
    }
    _write_json_atomic(output_dir / "manifest.json", manifest)
    return manifest


class BidBank:
    """Lazy loader for a completed persistent bid bank."""

    def __init__(self, root: str | Path, *, require_complete: bool = True):
        self.root = Path(root).resolve()
        manifest_path = self.root / "manifest.json"
        self.manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if int(self.manifest.get("version", -1)) != BID_BANK_VERSION:
            raise ValueError(f"unsupported bid bank version in {manifest_path}")
        self.entries = list(self.manifest.get("entries") or [])
        if not self.entries:
            raise ValueError(f"bid bank contains no entries: {manifest_path}")
        if require_complete and not bool(self.manifest.get("complete", False)):
            raise ValueError(f"bid bank is incomplete: {manifest_path}")
        self._by_date = {str(entry["service_date"]): entry for entry in self.entries}
        self._cache: dict[str, dict] = {}

    def __len__(self) -> int:
        return len(self.entries)

    def entry_for_date(self, service_date: str) -> dict:
        try:
            return self._by_date[str(service_date)]
        except KeyError as exc:
            raise KeyError(f"date {service_date!r} is not in bid bank {self.root}") from exc

    def load_entry(self, entry: dict) -> dict:
        relative_path = str(entry["bid_path"])
        if relative_path not in self._cache:
            self._cache[relative_path] = load_fixed_bid(self.root / relative_path)
        return self._cache[relative_path]

    def load_date(self, service_date: str) -> dict:
        return self.load_entry(self.entry_for_date(service_date))


def derive_bid_bank_observation_normalization(
    bid_bank: BidBank,
    *,
    build_episode: Callable,
    quantile: float = 0.95,
) -> dict:
    """Fit lower-controller observation scales to every training-bank signal."""

    from environment.normalize import derive_observation_normalization_profile

    # Demand is divided by each episode's own envelope.  Fit a separate,
    # bank-wide scale for that envelope so the ratio remains invertible without
    # leaking test-bank statistics.
    from environment.observation_config import BID_CONTEXT_FEATURES

    # Bid-lookahead values are already dimensionless ratios against the day's
    # known instruction envelope. Only physical-kW context features require a
    # fitted bank scale. Excluding the 72 half-day schedule features also
    # avoids retaining the same schedule once per command scenario.
    feature_names: tuple[str, ...] = tuple(
        name for name in BID_CONTEXT_FEATURES if name == "instruction_scale_kw"
    )
    samples = {"demand_kw": [], **{name: [] for name in feature_names}}
    scenario_episodes = 0
    for entry in bid_bank.entries:
        fixed_bid = bid_bank.load_entry(entry)
        scenario_count = max(
            len(fixed_bid.get("activation_scenario_payload") or []), 1
        )
        for scenario_idx in range(scenario_count):
            target, _tol, arrival_kwargs, _info = build_episode(
                fixed_bid, scenario_idx
            )
            samples["demand_kw"].append(
                np.asarray(target, dtype=np.float64).reshape(-1)
            )
            context = arrival_kwargs.get("market_context_series") or {}
            for feature_name in feature_names:
                samples[feature_name].append(
                    np.asarray(context.get(feature_name, []), dtype=np.float64).reshape(-1)
                )
            scenario_episodes += 1
    flattened = {
        name: np.concatenate(parts) if parts else np.empty(0, dtype=np.float64)
        for name, parts in samples.items()
    }
    profile = derive_observation_normalization_profile(
        flattened,
        quantile=float(quantile),
        source=str(bid_bank.root),
    )
    profile["bank_dates"] = int(len(bid_bank))
    profile["bank_scenario_episodes"] = int(scenario_episodes)
    return profile
