"""
Evaluation utilities for trained EV charging agents.

This module runs deterministic evaluation episodes outside the training loop.
It uses the held-out demand split, disables exploration noise, and writes
aggregate performance summaries. Detailed traces and PNG plots are collected
only when `enable_png=True`, so training-time interim tests can stay light.

Inputs:
- `test(agent, ...)` receives a trained agent object that exposes
  `set_test_mode()`, `episode_start()`, `episode_end()`, `update_active_evs()`,
  and `act()`.
- Demand episodes are loaded from `environment.readcsv.load_multiple_demand_files`
  using the test split unless `dataset_dir` is provided.
- EV arrivals and EV profiles are generated by `EVEnv`, using the same
  environment configuration as training.

Outputs:
- The returned `test_results` dictionary stores averaged rewards, per-episode
  traces, and performance metrics such as SoC miss rate, average SoC deficit,
  surplus absorption, and supply cooperation.
- When `save_test_detail_files=True`, lightweight CSV/history artifacts are
  saved in `results/TEST{test_episode_num}`. If `enable_png=True`, detailed
  CSV/plot artifacts are also generated there. The root-level
  `test_performance_metrics.*` and `test_episode_rewards_all.*` history files
  are controlled separately by `enable_history_png`. The root
  `results/test_history.json` is always updated so checkpoint-level test curves
  can be regenerated later.

Determinism:
- Evaluation temporarily seeds Python, NumPy, Torch, and CUDA RNGs with
  `ENV_SEED`, then restores the caller's RNG state before returning. This keeps
  checkpoint tests reproducible without perturbing subsequent training samples.
"""

import os
import csv
import json
import numpy as np
import torch
import random
import time
import traceback
import warnings

from environment.readcsv import load_multiple_demand_files ,load_multiple_demand_files_with_labels
from environment.EVEnv import EVEnv
from environment.arrival_context import ArrivalScenarioSampler
from environment.normalize import (
load_observation_normalization_for_archive ,
normalize_observation ,
)
from tools.Utils import (
plot_daily_rewards ,
plot_station_cooperation_full ,
plot_ev_detailed_soc ,
plot_performance_metrics ,
plot_arrival_counts ,
plot_reward_breakdown ,
plot_power_mismatch_analysis ,
)
from EnvConfig import TRAIN_USE_RESIDUAL_BESS
from Config import (
EPISODE_STEPS ,NUM_EVS ,NUM_STATIONS ,
ENV_SEED ,
USE_SWITCHING_CONSTRAINTS ,LOCAL_SWITCH_PENALTY ,
USE_STATION_TOTAL_POWER_LIMIT ,LOCAL_STATION_LIMIT_PENALTY ,
USE_DAY_CONTEXT_ARRIVALS ,
)


# Tracking errors stored per checkpoint in results/test_history.json.
_HISTORY_ERROR_KEYS =('raw_actor_mae_kw','pre_bess_mae_kw','post_bess_mae_kw')


def set_env_seed (seed =None ):
    if seed is not None :
        random .seed (seed )
        np .random .seed (seed )
        torch .manual_seed (seed )
        if torch .cuda .is_available ():
            torch .cuda .manual_seed_all (seed )


def _capture_rng_state ():
    """Snapshot global RNG state across random / numpy / torch (+ cuda)."""
    return {
    'py':random .getstate (),
    'np':np .random .get_state (),
    'torch':torch .get_rng_state (),
    'cuda':(torch .cuda .get_rng_state_all ()
    if torch .cuda .is_available ()else None ),
    }


def _restore_rng_state (state ):
    """Restore RNG state captured by `_capture_rng_state`."""
    if state is None :
        return
    try :
        random .setstate (state ['py'])
        np .random .set_state (state ['np'])
        torch .set_rng_state (state ['torch'])
        if state .get ('cuda')is not None and torch .cuda .is_available ():
            torch .cuda .set_rng_state_all (state ['cuda'])
    except Exception as exc :
        warnings .warn (f"Failed to restore evaluation RNG state: {exc}")


def _evaluation_episode_index (ep_idx ):
    """Return the stable zero-based scenario index for one evaluation rollout."""
    return max (0 ,int (ep_idx )-1 )


def _candidate_bid_bank_dirs (working_dir ):
    """Bank directories that might hold the bid for the episode being plotted.

    The EnvConfig constant is only the default bank. A run launched with
    --bank-dir/--test-bank-dir uses a different one and never writes it back
    into EnvConfig, so consulting the constant alone finds a bid for the right
    date from the wrong bank, the tolerance check below rejects it, and the
    plot silently loses its envelope. The run's own resume manifest records
    the banks it was actually given, so read that first.
    """

    candidates =[]

    def _add (value ):
        if not value :
            return
        text =str (value )
        if text not in candidates :
            candidates .append (text )

    if working_dir :
        manifest =os .path .join (str (working_dir ),"resume","latest.json")
        try :
            with open (manifest ,encoding ="utf-8")as handle :
                context =(json .load (handle )or {}).get ("context")or {}
            _add ((context .get ("test_bid_bank")or {}).get ("path"))
            _add ((context .get ("train_bid_bank")or {}).get ("path"))
        except Exception :
            pass

    try :
        from EnvConfig import (
        LOWER_TRAIN_UPPER_BID_TEST_BANK_DIR ,
        LOWER_TRAIN_UPPER_BID_BANK_DIR ,
        )
        _add (LOWER_TRAIN_UPPER_BID_TEST_BANK_DIR )
        _add (LOWER_TRAIN_UPPER_BID_BANK_DIR )
    except Exception :
        pass

    # A run that has not written its first resume manifest yet, and whose
    # banks are not the EnvConfig defaults, is otherwise unreachable. Its bank
    # still sits beside the ones above, so offer those as a last resort. The
    # tolerance check decides which one is right, so a wider list costs a few
    # rejected reads and cannot produce a wrong envelope.
    for known in list (candidates ):
        parent =os .path .dirname (str (known ))
        if not parent or not os .path .isdir (parent ):
            continue
        for name in sorted (os .listdir (parent )):
            sibling =os .path .join (parent ,name )
            if os .path .isdir (sibling ):
                _add (sibling )

    return candidates


def _bid_envelope_for_env (local_env ,service_date ,working_dir =None ):
    """Per-step baseline and bid envelope for the episode the env was reset to.

    Each candidate bank is looked up by date and then checked against the
    tolerance series the environment actually holds: for the right bid the
    implied band -- frac*up or frac*down while an instruction is running,
    frac*(up+down) while it is not -- reproduces that series step for step.
    The first candidate that reproduces it wins; one that fails is skipped,
    so a plot never shows a baseline belonging to a different day or a
    different bank rather than silently mislabelling one. Widening the search
    cannot loosen that: the check is what decides, not the order.
    """

    try :
        from training .bid_bank import BidBank
        from market .bid_env import STEPS_PER_BLOCK
    except Exception :
        return None

    target =getattr (local_env ,"net_demand_series_cpu",None )
    tol =getattr (local_env ,"_tol_narrow_series",None )
    if target is None or tol is None :
        return None
    target =np .asarray (target ,dtype =float ).reshape (-1 )
    tol =np .asarray (tol ,dtype =float ).reshape (-1 )
    steps =min (target .size ,tol .size )
    if steps ==0 :
        return None

    block =np .arange (steps )//STEPS_PER_BLOCK

    for bank_dir in _candidate_bid_bank_dirs (working_dir ):
        try :
            fixed_bid =BidBank (bank_dir ).load_date (str (service_date ))
            baseline =np .asarray (fixed_bid ["baseline_plan"],dtype =float )
            up =np .asarray (fixed_bid ["up_plan"],dtype =float )
            down =np .asarray (fixed_bid ["down_plan"],dtype =float )
            frac =float (fixed_bid .get ("assessment_band_fraction")or 0.1 )
        except Exception :
            continue

        if block .max (initial =0 )>=baseline .size :
            continue
        baseline_by_step =baseline [block ]
        up_by_step =up [block ]
        down_by_step =down [block ]

        # The target series is stored float32, so an idle step lands within a
        # few ULPs of the float64 baseline rather than exactly on it. At 1e3 kW
        # that gap is ~1e-4, which a fixed 1e-6 test reads as a live
        # instruction. Scale the deadzone with the magnitude involved; 1 mW is
        # physically nothing.
        regulation =target [:steps ]-baseline_by_step
        idle_eps =np .maximum (1e-3 ,1e-6 *np .abs (baseline_by_step ))
        expected =np .where (
        regulation <-idle_eps ,frac *up_by_step ,
        np .where (regulation >idle_eps ,frac *down_by_step ,frac *(up_by_step +down_by_step )),
        )
        expected =np .maximum (expected ,1e-6 )
        if not np .allclose (expected ,tol [:steps ],atol =1e-3 ,rtol =1e-4 ):
            continue

        return {
        "baseline":baseline_by_step ,
        "lower":baseline_by_step -up_by_step ,
        "upper":baseline_by_step +down_by_step ,
        }

    return None


def _summarize_test_results (test_results ):
    pm =test_results .get ('performance_metrics',{})if test_results else {}

    def _mean (values ,default =0.0 ):
        if not values :
            return default
        arr =np .asarray (values ,dtype =np .float64 )
        if arr .size ==0 :
            return default
        return float (np .mean (arr ))

    def _sum_int (values ):
        if not values :
            return 0
        return int (np .sum (np .asarray (values ,dtype =np .float64 )))

    local_reward =_mean (test_results .get ('all_local_rewards',[])if test_results else [])
    global_reward =_mean (test_results .get ('all_global_rewards',[])if test_results else [])
    soc_miss =_mean (pm .get ('soc_miss_count',[]))
    soc_hit =100.0 -soc_miss
    central_soc_miss =_mean (pm .get ('central_soc_miss_count',[]))
    central_soc_hit =100.0 -central_soc_miss
    avg_soc_deficit =_mean (pm .get ('avg_soc_deficit',[]))
    surplus_steps =_sum_int (pm .get ('surplus_steps',[]))
    surplus_within =_sum_int (pm .get ('surplus_within_narrow',[]))
    shortage_steps =_sum_int (pm .get ('shortage_steps',[]))
    shortage_within =_sum_int (pm .get ('shortage_within_narrow',[]))
    zero_steps =_sum_int (pm .get ('zero_request_steps',[]))
    zero_within =_sum_int (pm .get ('zero_request_within_narrow',[]))
    dispatch_steps =surplus_steps +shortage_steps +zero_steps
    dispatch_within =surplus_within +shortage_within +zero_within
    dispatch_rate =(dispatch_within /dispatch_steps *100.0 )if dispatch_steps >0 else 0.0
    system_surplus_steps =_sum_int (pm .get ('system_surplus_steps',[]))
    system_surplus_within =_sum_int (pm .get ('system_surplus_within_narrow',[]))
    system_shortage_steps =_sum_int (pm .get ('system_shortage_steps',[]))
    system_shortage_within =_sum_int (pm .get ('system_shortage_within_narrow',[]))
    system_zero_steps =_sum_int (pm .get ('system_zero_request_steps',[]))
    system_zero_within =_sum_int (pm .get ('system_zero_request_within_narrow',[]))
    system_dispatch_steps =system_surplus_steps +system_shortage_steps +system_zero_steps
    system_dispatch_within =system_surplus_within +system_shortage_within +system_zero_within
    system_dispatch_rate =(
    system_dispatch_within /system_dispatch_steps *100.0
    if system_dispatch_steps >0 else 0.0
    )
    central_surplus_steps =_sum_int (pm .get ('central_surplus_steps',[]))
    central_surplus_within =_sum_int (pm .get ('central_surplus_within_narrow',[]))
    central_shortage_steps =_sum_int (pm .get ('central_shortage_steps',[]))
    central_shortage_within =_sum_int (pm .get ('central_shortage_within_narrow',[]))
    central_zero_steps =_sum_int (pm .get ('central_zero_request_steps',[]))
    central_zero_within =_sum_int (pm .get ('central_zero_request_within_narrow',[]))
    central_dispatch_steps =central_surplus_steps +central_shortage_steps +central_zero_steps
    central_dispatch_within =central_surplus_within +central_shortage_within +central_zero_within
    central_dispatch_rate =(
    central_dispatch_within /central_dispatch_steps *100.0
    if central_dispatch_steps >0 else 0.0
    )
    surplus_rate =(surplus_within /surplus_steps *100.0 )if surplus_steps >0 else 0.0
    supply_rate =(shortage_within /shortage_steps *100.0 )if shortage_steps >0 else 0.0
    departing_evs =_sum_int (pm .get ('departing_evs',[]))
    departing_evs_soc_met =_sum_int (pm .get ('departing_evs_soc_met',[]))
    central_departing_evs_soc_met =_sum_int (pm .get ('central_departing_evs_soc_met',[]))
    num_episodes =len (test_results .get ('all_rewards',[])if test_results else [])
    return {
    'num_episodes':num_episodes ,
    'local_reward':local_reward ,
    'global_reward':global_reward ,
    'soc_hit':soc_hit ,
    'central_soc_hit':central_soc_hit ,
    'avg_soc_deficit':avg_soc_deficit ,
    'dispatch_rate':dispatch_rate ,
    'system_dispatch_rate':system_dispatch_rate ,
    'central_dispatch_rate':central_dispatch_rate ,
    'raw_actor_mae_kw':_mean (pm .get ('raw_actor_mae_kw',[])),
    'pre_bess_mae_kw':_mean (pm .get ('pre_bess_mae_kw',[])),
    'post_bess_mae_kw':_mean (pm .get ('post_bess_mae_kw',[])),
    'bess_final_soc_pct':_mean (pm .get ('bess_final_soc_pct',[])),
    'bess_max_abs_power_kw':max (pm .get ('bess_max_abs_power_kw',[])or [0.0 ]),
    'bess_throughput_kwh':_mean (pm .get ('bess_throughput_kwh',[])),
    'surplus_rate':surplus_rate ,
    'supply_rate':supply_rate ,
    'departing_evs':departing_evs ,
    'departing_evs_soc_met':departing_evs_soc_met ,
    'central_departing_evs_soc_met':central_departing_evs_soc_met ,
    'surplus_steps':surplus_steps ,
    'surplus_within':surplus_within ,
    'shortage_steps':shortage_steps ,
    'shortage_within':shortage_within ,
    'dispatch_steps':dispatch_steps ,
    'dispatch_within':dispatch_within ,
    'system_dispatch_steps':system_dispatch_steps ,
    'system_dispatch_within':system_dispatch_within ,
    'central_dispatch_steps':central_dispatch_steps ,
    'central_dispatch_within':central_dispatch_within ,
    }


def _print_test_summary (test_results ,test_episode_num =None ,duration_sec =None ):
    summary =_summarize_test_results (test_results )
    label ="TEST" if test_episode_num is None else f"TEST{test_episode_num}"
    duration_part ="" if duration_sec is None else f" | duration={duration_sec:.1f}s"
    # With the battery off the system column is the central column and the third
    # MAE is the second, so both would print the same number twice.
    if bool (TRAIN_USE_RESIDUAL_BESS ):
        _rates =(
        f"MARL/Central/System={summary['dispatch_rate']:.2f}/"
        f"{summary['central_dispatch_rate']:.2f}/{summary['system_dispatch_rate']:.2f}%"
        )
        _mae =(
        f"MAE={summary['raw_actor_mae_kw']:.1f}->"
        f"{summary['pre_bess_mae_kw']:.1f}->{summary['post_bess_mae_kw']:.1f}kW"
        )
        _bess =(
        f" | BESS max={summary['bess_max_abs_power_kw']:.1f}kW"
        f", SoC={summary['bess_final_soc_pct']:.1f}%"
        )
    else :
        _rates =(
        f"MARL/Central={summary['dispatch_rate']:.2f}/"
        f"{summary['central_dispatch_rate']:.2f}%"
        )
        _mae =(
        f"MAE={summary['raw_actor_mae_kw']:.1f}->"
        f"{summary['pre_bess_mae_kw']:.1f}kW"
        )
        _bess =""
    print (
    f"[{label} summary] episodes={summary['num_episodes']}"
    f" | local={summary['local_reward']:.4f}"
    f" | global={summary['global_reward']:.4f}"
    f" | SoC actor/physical={summary['soc_hit']:.2f}/"
    f"{summary['central_soc_hit']:.2f}%"
    f" ({summary['departing_evs_soc_met']}/"
    f"{summary['central_departing_evs_soc_met']}/"
    f"{summary['departing_evs']} EV)"
    f" | deficit={summary['avg_soc_deficit']:.2f}kWh"
    f" | {_rates}"
    f" | {_mae}"
    f"{_bess}"
    # Not a battery figure: the numerator and denominator of the MARL column.
    f" ({summary['dispatch_within']}/{summary['dispatch_steps']} MARL steps)"
    f" | surplus={summary['surplus_rate']:.2f}%"
    f" | supply={summary['supply_rate']:.2f}%"
    f"{duration_part}"
    )


def _episode_payload_to_series_and_date (payload ,episode_steps ):
    service_date =None
    if isinstance (payload ,dict ):
        service_date =payload .get ("date")
        payload =payload .get ("series")
    data =np .asarray (payload ,dtype =float ).reshape (-1 )
    if data .size ==0 :
        raise ValueError ("Demand episode is empty.")
    if data .size >=int (episode_steps ):
        return data [:int (episode_steps )],service_date
    return np .pad (data ,(0 ,int (episode_steps )-int (data .size ))),service_date


def _reset_env_with_day_context (
env ,
episode_demand ,
service_date ,
arrival_sampler ,
tol_narrow_series =None ,
arrival_probabilities_by_station =None ,
day_context =None ,
market_context_series =None ,
):
    kwargs ={"net_demand_series":episode_demand ,"service_date":service_date }
    if tol_narrow_series is not None :
        kwargs ["tol_narrow_series"]=tol_narrow_series
    if market_context_series is not None :
        kwargs ["market_context_series"]=market_context_series
    if arrival_probabilities_by_station is not None :
        kwargs ["arrival_probabilities_by_station"]=arrival_probabilities_by_station
        if day_context is not None :
            kwargs ["day_context"]=day_context
    elif arrival_sampler is not None :
        scenario =arrival_sampler .scenario_for_day (service_date )
        kwargs ["arrival_probabilities_by_station"]=scenario .arrival_probabilities_by_station
        kwargs ["day_context"]=scenario .day_context
    return env .reset (**kwargs )




def test (
agent ,
random_window =True ,
working_dir =None ,
test_results =None ,
test_episode_num =None ,
dataset_dir =None ,
demand_data_override =None ,
arrival_sampler_override =None ,
episode_preparer =None ,
num_episodes =None ,
eval_seed =ENV_SEED ,
enable_png =False ,
enable_history_png =True ,
save_test_detail_files =True ,
update_history =True ,
verbose =True ,
print_summary =None ,
):
    """
    Run deterministic test episodes for one agent/checkpoint.
    """
    if print_summary is None :
        print_summary =bool (verbose )
    test_begin_time =time .time ()
    enable_switch_metrics =bool (USE_SWITCHING_CONSTRAINTS )or float (LOCAL_SWITCH_PENALTY )!=0.0
    enable_stlimit_metrics =bool (USE_STATION_TOTAL_POWER_LIMIT )or float (LOCAL_STATION_LIMIT_PENALTY )!=0.0

    rng_state =_capture_rng_state ()

    if working_dir is None :
        working_dir =os .getcwd ()
    load_observation_normalization_for_archive (working_dir )

    demand_data_test =None
    arrival_sampler =None
    if demand_data_override is not None :
        demand_data_test =list (demand_data_override )
    else :
        try :
            if dataset_dir is not None :
                if bool (USE_DAY_CONTEXT_ARRIVALS ):
                    all_demand_data =load_multiple_demand_files_with_labels (directory =dataset_dir ,train_split =25 )
                else :
                    all_demand_data =load_multiple_demand_files (directory =dataset_dir ,train_split =25 )
                demand_data_test =all_demand_data ['test']
            else :
                if bool (USE_DAY_CONTEXT_ARRIVALS ):
                    all_demand_data =load_multiple_demand_files_with_labels (train_split =25 )
                else :
                    all_demand_data =load_multiple_demand_files (train_split =25 )
                demand_data_test =all_demand_data ['test']
        except FileNotFoundError :
            error_message ="Failed to load test demand CSV files."
            print (error_message )
            raise

    agent .set_test_mode (True )

    original_use_tensorboard =None
    if hasattr (agent ,'use_tensorboard'):
        original_use_tensorboard =agent .use_tensorboard
        agent .use_tensorboard =False

    if test_results is None :
        test_results ={
        'all_rewards':[],
        'all_local_rewards':[],
        'all_global_rewards':[],
        'all_episode_data':{},
        'performance_metrics':{
        'soc_miss_count':[],
        'avg_soc_deficit':[],
        'surplus_absorption_rate':[],
        'supply_cooperation_rate':[],
        'departing_evs':[],
        'departing_evs_soc_met':[],
        'central_soc_miss_count':[],
        'central_avg_soc_deficit':[],
        'central_departing_evs_soc_met':[],
        'surplus_steps':[],
        'surplus_within_narrow':[],
        'shortage_steps':[],
        'shortage_within_narrow':[],
        'zero_request_steps':[],
        'zero_request_within_narrow':[],
        'system_surplus_steps':[],
        'system_surplus_within_narrow':[],
        'system_shortage_steps':[],
        'system_shortage_within_narrow':[],
        'system_zero_request_steps':[],
        'system_zero_request_within_narrow':[],
        'central_surplus_steps':[],
        'central_surplus_within_narrow':[],
        'central_shortage_steps':[],
        'central_shortage_within_narrow':[],
        'central_zero_request_steps':[],
        'central_zero_request_within_narrow':[],
        'central_tracking_success_rate':[],
        'raw_actor_mae_kw':[],
        'central_corrected_ev_steps':[],
        'central_corrected_station_steps':[],
        'central_correction_active_steps':[],
        'central_absolute_correction_kwh':[],
        'central_max_abs_aggregate_correction_kw':[],
        'central_max_corrected_evs_per_step':[],
        'central_max_corrected_stations_per_step':[],
        'central_max_station_target_error_kw':[],
        'system_tracking_success_rate':[],
        'pre_bess_mae_kw':[],
        'post_bess_mae_kw':[],
        'bess_final_soc_pct':[],
        'bess_throughput_kwh':[],
        'bess_power_limit_hits':[],
        'bess_energy_limit_hits':[],
        'bess_max_abs_power_kw':[],
        }
        }
        if enable_switch_metrics :
            test_results ['performance_metrics']['avg_switches']=[]
        if enable_stlimit_metrics :
            test_results ['performance_metrics']['station_limit_hits']=[]
            test_results ['performance_metrics']['station_limit_steps']=[]
            test_results ['performance_metrics']['station_charge_limit_hits']=[]
            test_results ['performance_metrics']['station_discharge_limit_hits']=[]
            test_results ['performance_metrics']['station_limit_penalty_total']=[]

    if arrival_sampler_override is not None :
        arrival_sampler =arrival_sampler_override
    elif bool (USE_DAY_CONTEXT_ARRIVALS ):
        arrival_sampler =ArrivalScenarioSampler ()

    episode_soc_stats =[]
    collect_episode_detail =bool (enable_png and save_test_detail_files )


    def run_single_test_episode (ep_idx ):
        """
        Roll out one deterministic evaluation episode.

        The policy is evaluated without exploration noise. Detailed per-step
        records are collected so the same rollout can support scalar metrics,
        station-cooperation plots, EV SoC trajectories, reward decomposition,
        and power-mismatch diagnostics.
        """

        collect_soc_detail =bool (
        collect_episode_detail and ep_idx >max (0 ,int (num_test_episodes )-2 )
        )
        collect_reward_detail =collect_soc_detail
        collect_latest_detail =bool (collect_episode_detail and ep_idx ==int (num_test_episodes ))
        local_env =EVEnv (num_stations =NUM_STATIONS ,num_evs =NUM_EVS ,episode_steps =EPISODE_STEPS )
        local_env .use_residual_bess =bool (TRAIN_USE_RESIDUAL_BESS )
        local_env .record_snapshots =collect_soc_detail

        local_agent =agent

        if not demand_data_test :
            raise RuntimeError ("Test demand pool is empty; cannot run evaluation episodes.")
        data_idx =(ep_idx -1 )%len (demand_data_test )
        episode_demand ,service_date =_episode_payload_to_series_and_date (
        demand_data_test [data_idx ],local_env .episode_steps
        )
        tol_narrow_series =None
        arrival_kwargs ={}
        evaluation_episode_idx =_evaluation_episode_index (ep_idx )
        if episode_preparer is not None :
            episode_preparer (local_env ,episode_demand ,service_date ,arrival_sampler ,
            evaluation_episode_idx )
        else :
            from training.lower_bid_training import build_upper_bid_training_episode

            scenario =arrival_sampler .scenario_for_day (service_date )if arrival_sampler is not None else None
            augment_episode_idx =evaluation_episode_idx
            episode_demand ,tol_narrow_series ,arrival_kwargs ,_bid_info =build_upper_bid_training_episode (
            episode_demand ,
            service_date ,
            augment_episode_idx ,
            arrival_scenario =scenario ,
            )
            _reset_env_with_day_context (
            local_env ,
            episode_demand ,
            service_date ,
            None ,
            tol_narrow_series =tol_narrow_series ,
            arrival_probabilities_by_station =arrival_kwargs .get ("arrival_probabilities_by_station"),
            day_context =arrival_kwargs .get ("day_context"),
            market_context_series =arrival_kwargs .get ("market_context_series"),
            )

        # Per-step (baseline, bid-envelope-lower, bid-envelope-upper) for the
        # station-cooperation plot. Read back from the environment after reset
        # so it covers both paths above, including the bank preparer the
        # production pretrain uses. None when the bid cannot be confirmed.
        bid_envelope_by_step =_bid_envelope_for_env (local_env ,service_date ,working_dir )

        local_agent .episode_start ()

        ep_data ={}
        if collect_episode_detail :
            ep_data ={
            'ag_requests':[],'total_ev_transport':[],'soc_data':{},
            'tol_narrow':[],
            'baseline':[],'bid_envelope_lower':[],'bid_envelope_upper':[],
            'tracking_enabled':[],
            'pre_bess_residual_kw':[],
            'raw_actor_total_power_kw':[],
            'raw_actor_residual_kw':[],
            'central_correction_power_kw':[],
            'bess_power_kw':[],
            'bess_soc_pct':[],
            'pcc_power_kw':[],
            'post_bess_residual_kw':[],
            }
            if collect_latest_detail :
                ep_data ['power_mismatch']=[]
                ep_data ['arrivals_per_step']=[]
            if collect_reward_detail :
                ep_data ['rewards_global_balance']=[]
                ep_data ['rewards_local_shaping']=[]
                ep_data ['rewards_local_departure']=[]
                ep_data ['rewards_local_discharge_penalty']=[]
                ep_data ['rewards_local_switch_penalty']=[]
                ep_data ['rewards_local_station_limit_penalty']=[]

            if collect_soc_detail :
                for station_idx in range (local_env .num_stations ):
                    ep_data ['soc_data'][f'station{station_idx+1}']={}
                    for ev_idx ,ev in enumerate (local_env .stations_evs [station_idx ]):
                        ev_id =str (ev ['id'])
                        ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]={
                        'id':ev ['id'],
                        'station':station_idx ,
                        'depart':ev ['depart'],
                        'target':ev ['target'],
                        'times':[int (local_env .step_count )],
                        'soc':[float (ev ['soc'])]
                        }

            for i in range (1 ,local_env .num_stations +1 ):ep_data [f'actual_ev{i}']=[]

        ep_r ,ep_local_r ,ep_global_r =0.0 ,0.0 ,0.0

        while True :
            obs =local_env .begin_step ()
            obs =normalize_observation (obs )
            act =local_agent .act (obs ,env =local_env ,noise =False )
            _ ,r_l ,r_g ,done ,info =local_env .apply_action (
            act ,build_info =collect_episode_detail ,return_observation =False ,
            include_active_evs =False ,include_ev_physics =False ,
            include_reward_breakdown =collect_reward_detail
            )


            if torch .is_tensor (r_l ):
                local_sum =float (r_l .detach ().sum ().item ())
                local_mean =float (r_l .detach ().mean ().item ())
            else :
                local_sum =float (sum (r_l ))
                local_mean =float (np .mean (r_l ))
            ep_r +=local_sum +float (r_g )
            ep_local_r +=local_mean
            ep_global_r +=float (r_g )

            if collect_episode_detail :
                ep_data ['ag_requests'].append (info ['net_demand'])
                ep_data ['total_ev_transport'].append (info ['total_ev_transport'])
                ep_data ['tol_narrow'].append (float (local_env .tol_narrow_metrics ))
                if bid_envelope_by_step is not None :
                    _envelope_step =local_env .step_count -1
                    ep_data ['baseline'].append (float (bid_envelope_by_step ['baseline'][_envelope_step ]))
                    ep_data ['bid_envelope_lower'].append (float (bid_envelope_by_step ['lower'][_envelope_step ]))
                    ep_data ['bid_envelope_upper'].append (float (bid_envelope_by_step ['upper'][_envelope_step ]))
                ep_data ['tracking_enabled'].append (bool (info .get ('tracking_enabled',True )))
                ep_data ['pre_bess_residual_kw'].append (float (info .get ('pre_bess_residual_kw',0.0 )))
                ep_data ['raw_actor_total_power_kw'].append (float (info .get ('raw_actor_total_power_kw',info ['total_ev_transport'])))
                ep_data ['raw_actor_residual_kw'].append (float (info .get ('raw_actor_residual_kw',0.0 )))
                ep_data ['central_correction_power_kw'].append (float (info .get ('central_correction_power_kw',0.0 )))
                ep_data ['bess_power_kw'].append (float (info .get ('bess_power_kw',0.0 )))
                ep_data ['bess_soc_pct'].append (float (info .get ('bess_soc_pct',0.0 )))
                ep_data ['pcc_power_kw'].append (float (info .get ('pcc_power_kw',info ['total_ev_transport'])))
                ep_data ['post_bess_residual_kw'].append (float (info .get ('post_bess_residual_kw',info ['net_demand']-info ['total_ev_transport'])))
                if collect_latest_detail :
                    ep_data ['power_mismatch'].append (info ['net_demand']-info ['total_ev_transport'])


                    ep_data ['arrivals_per_step'].append (
                    info .get ('arrivals_by_station',info .get ('arrivals_this_step',0 ))
                    )


                current_step =int (info .get ('step_count',local_env .step_count ))
                if collect_soc_detail :
                    for station_idx in range (local_env .num_stations ):
                        if f'station{station_idx+1}'not in ep_data ['soc_data']:
                            ep_data ['soc_data'][f'station{station_idx+1}']={}
                        for ev_idx ,ev in enumerate (local_env .stations_evs [station_idx ]):
                            ev_id =str (ev ['id'])
                            if ev_id not in ep_data ['soc_data'][f'station{station_idx+1}']:
                                ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]={
                                'id':ev ['id'],
                                'station':station_idx ,
                                'depart':ev ['depart'],
                                'target':ev ['target'],
                                'times':[current_step ],
                                'soc':[float (ev ['soc'])]
                                }
                            else :
                                ev_times =ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['times']
                                if len (ev_times )>0 and ev_times [-1 ]==current_step :
                                    ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['soc'][-1 ]=float (ev ['soc'])
                                else :
                                    ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['times'].append (current_step )
                                    ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['soc'].append (float (ev ['soc']))


                if collect_soc_detail and 'departed_evs'in info and info ['departed_evs']:
                    for departed_ev in info ['departed_evs']:
                        ev_id =str (departed_ev .get ('id'))
                        station_idx =departed_ev .get ('station')
                        if station_idx is not None and ev_id in ep_data ['soc_data'][f'station{station_idx+1}']:
                            after_list =info .get ('snapshot_after',{}).get (station_idx ,[])
                            matched =next ((d for d in after_list if str (d .get ('id'))==ev_id ),None )
                            if matched is not None :
                                ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['final_soc']=float (matched .get ('new_soc',0.0 ))
                                ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['target_soc']=float (matched .get ('target_soc',0.0 ))
                            ep_data ['soc_data'][f'station{station_idx+1}'][ev_id ]['depart_step']=current_step

                if collect_reward_detail and 'reward_breakdown'in info :
                    rb =info ['reward_breakdown']
                    ep_data ['rewards_global_balance'].append (rb ['global'].get ('balance_reward',0.0 ))
                    ep_data ['rewards_local_shaping'].append (sum (s .get ('progress_shaping',0.0 )for s in rb ['per_station']))
                    ep_data ['rewards_local_departure'].append (sum (s .get ('departure_reward',0.0 )for s in rb ['per_station']))
                    ep_data ['rewards_local_discharge_penalty'].append (sum (s .get ('discharge_penalty',0.0 )for s in rb ['per_station']))
                    ep_data ['rewards_local_switch_penalty'].append (sum (s .get ('switch_penalty',0.0 )for s in rb ['per_station']))
                    ep_data ['rewards_local_station_limit_penalty'].append (sum (s .get ('station_limit_penalty',0.0 )for s in rb ['per_station']))

                station_powers =info ['station_powers']
                for st_idx in range (local_env .num_stations ):
                    s_sum =float (station_powers [st_idx ])
                    ep_data [f'actual_ev{st_idx+1}'].append (s_sum )

            if all (done ):
                break

        local_agent .episode_end ()
        metrics =local_env .get_metrics ()


        arrival_log =np .asarray (getattr (local_env ,'arrival_soc_log',[]),dtype =np .float64 )
        needed_log =np .asarray (getattr (local_env ,'arrival_needed_log',[]),dtype =np .float64 )
        dwell_log =np .asarray (getattr (local_env ,'arrival_dwell_log',[]),dtype =np .float64 )

        def _stats (arr :np .ndarray ):
            if arr .size ==0 :return 0.0 ,0.0 ,0.0 ,0.0
            return float (arr .mean ()),float (arr .max ()),float (arr .min ()),float (arr .std (ddof =0 ))

        arrival_mean ,arrival_max ,arrival_min ,arrival_std =_stats (arrival_log )
        needed_mean ,needed_max ,needed_min ,needed_std =_stats (needed_log )
        dwell_mean ,dwell_max ,dwell_min ,dwell_std =_stats (dwell_log )

        soc_stat ={
        'episode':ep_idx ,
        'arrival_mean':arrival_mean ,'arrival_max':arrival_max ,'arrival_min':arrival_min ,'arrival_std':arrival_std ,
        'needed_mean':needed_mean ,'needed_max':needed_max ,'needed_min':needed_min ,'needed_std':needed_std ,
        'dwell_mean':dwell_mean ,'dwell_max':dwell_max ,'dwell_min':dwell_min ,'dwell_std':dwell_std ,
        'count':int (arrival_log .size ),
        }

        return ep_idx ,ep_r ,ep_local_r ,ep_global_r ,ep_data ,metrics ,local_env .step_count ,soc_stat

    set_env_seed (eval_seed )
    try :


        if num_episodes is not None :
            num_test_episodes =int (num_episodes )
        else :
            num_test_episodes =min (5 ,len (demand_data_test ))if demand_data_test else 0
        if num_test_episodes <=0 :
            raise RuntimeError ("num_test_episodes resolved to 0; check num_episodes and demand_data_test.")

        all_results =[]


        for ep in range (1 ,num_test_episodes +1 ):
            t_start =time .time ()
            res =run_single_test_episode (ep )
            duration =time .time ()-t_start
            all_results .append (res )


            ep_idx ,ep_r ,ep_local_r ,ep_global_r ,_ ,metrics ,steps_in_ep ,_ =res
            parts =[
            f"test{ep_idx}",
            f"SoC hit: {100-metrics['soc_miss_rate']:.1f}%",
            f"Avg SoC deficit: {metrics.get('avg_soc_deficit', 0.0):.2f} kWh",
            ]
            if enable_switch_metrics :
                parts .append (f"Avg Switches: {metrics.get('avg_switches', 0.0):.2f}")
            if enable_stlimit_metrics :
                parts .append (
                f"StLimit: steps={metrics.get('station_limit_steps', 0)}, hits={metrics.get('station_limit_hits', 0)}, pen={metrics.get('station_limit_penalty_total', 0.0):.2f}"
                )
            parts .append (
            f"Surplus: {metrics['surplus_within_narrow']}/{metrics['surplus_steps']} ({metrics['surplus_absorption_rate']:.1f}%)"
            )
            parts .append (
            f"Supply: {metrics['shortage_within_narrow']}/{metrics['shortage_steps']} ({metrics['supply_cooperation_rate']:.1f}%)"
            )
            parts .append (
            f"MARL/Central/System: {metrics.get('tracking_success_rate', 0.0):.1f}/"
            f"{metrics.get('central_tracking_success_rate', 0.0):.1f}/"
            f"{metrics.get('system_tracking_success_rate', 0.0):.1f}% "
            f"(MAE {metrics.get('raw_actor_mae_kw', 0.0):.1f}->"
            f"{metrics.get('pre_bess_mae_kw', 0.0):.1f}->"
            f"{metrics.get('post_bess_mae_kw', 0.0):.1f} kW)"
            )
            parts .append (
            f"BESS: SoC={metrics.get('bess_final_soc_pct', 0.0):.1f}%, "
            f"max={metrics.get('bess_max_abs_power_kw', 0.0):.1f}kW"
            )
            parts .append (f"Duration={duration:.1f}s")
            if verbose :
                print (" | ".join (parts ))


        for res in all_results :
            ep_idx ,ep_r ,ep_local_r ,ep_global_r ,ep_data ,metrics ,steps_in_ep ,soc_stat =res

            test_results ['all_rewards'].append (ep_r /steps_in_ep )
            test_results ['all_local_rewards'].append (ep_local_r /steps_in_ep )
            test_results ['all_global_rewards'].append (ep_global_r /steps_in_ep )
            if collect_episode_detail :
                test_results ['all_episode_data'][ep_idx ]=ep_data

            pm =test_results ['performance_metrics']
            pm ['soc_miss_count'].append (metrics ['soc_miss_rate'])
            if enable_switch_metrics :
                pm ['avg_switches']=pm .get ('avg_switches',[])
                pm ['avg_switches'].append (metrics .get ('avg_switches',0.0 ))
            pm ['avg_soc_deficit']=pm .get ('avg_soc_deficit',[])
            pm ['avg_soc_deficit'].append (metrics .get ('avg_soc_deficit',0.0 ))
            pm ['surplus_absorption_rate'].append (metrics ['surplus_absorption_rate'])
            pm ['supply_cooperation_rate'].append (metrics ['supply_cooperation_rate'])
            pm ['departing_evs'].append (metrics .get ('departing_evs',0 ))
            pm ['departing_evs_soc_met'].append (metrics .get ('departing_evs_soc_met',0 ))
            pm .setdefault ('central_soc_miss_count',[]).append (metrics .get ('central_soc_miss_rate',0.0 ))
            pm .setdefault ('central_avg_soc_deficit',[]).append (metrics .get ('central_avg_soc_deficit',0.0 ))
            pm .setdefault ('central_departing_evs_soc_met',[]).append (metrics .get ('central_departing_evs_soc_met',0 ))
            pm ['surplus_steps'].append (metrics ['surplus_steps'])
            pm ['surplus_within_narrow'].append (metrics ['surplus_within_narrow'])
            pm ['shortage_steps'].append (metrics ['shortage_steps'])
            pm ['shortage_within_narrow'].append (metrics ['shortage_within_narrow'])
            pm ['zero_request_steps'].append (metrics .get ('zero_request_steps',0 ))
            pm ['zero_request_within_narrow'].append (metrics .get ('zero_request_within_narrow',0 ))
            for key in (
            'system_surplus_steps','system_surplus_within_narrow',
            'system_shortage_steps','system_shortage_within_narrow',
            'system_zero_request_steps','system_zero_request_within_narrow',
            'central_surplus_steps','central_surplus_within_narrow',
            'central_shortage_steps','central_shortage_within_narrow',
            'central_zero_request_steps','central_zero_request_within_narrow',
            'central_tracking_success_rate','raw_actor_mae_kw',
            'central_corrected_ev_steps','central_corrected_station_steps',
            'central_correction_active_steps',
            'central_absolute_correction_kwh','central_max_abs_aggregate_correction_kw',
            'central_max_corrected_evs_per_step','central_max_corrected_stations_per_step',
            'central_max_station_target_error_kw',
            'system_tracking_success_rate','pre_bess_mae_kw','post_bess_mae_kw',
            'bess_final_soc_pct','bess_throughput_kwh','bess_power_limit_hits',
            'bess_energy_limit_hits','bess_max_abs_power_kw',
            ):
                pm .setdefault (key ,[]).append (metrics .get (key ,0.0 ))
            if enable_stlimit_metrics :
                pm .setdefault ('station_limit_hits',[]).append (metrics .get ('station_limit_hits',0 ))
                pm .setdefault ('station_limit_steps',[]).append (metrics .get ('station_limit_steps',0 ))
                pm .setdefault ('station_charge_limit_hits',[]).append (metrics .get ('station_charge_limit_hits',0 ))
                pm .setdefault ('station_discharge_limit_hits',[]).append (metrics .get ('station_discharge_limit_hits',0 ))
                pm .setdefault ('station_limit_penalty_total',[]).append (metrics .get ('station_limit_penalty_total',0.0 ))

            episode_soc_stats .append (soc_stat )

    except Exception :
        traceback .print_exc ()

    finally :

        if save_test_detail_files :
            if test_episode_num is None :
                raise ValueError ("test_episode_num is required for deterministic result directory naming.")
            results_dir =os .path .join (working_dir ,'results',f'TEST{test_episode_num}')
        else :
            results_dir =os .path .join (working_dir ,'results')
        os .makedirs (results_dir ,exist_ok =True )

        if save_test_detail_files and episode_soc_stats :
            soc_summary_path =os .path .join (results_dir ,'episode_soc_summary.csv')
            try :
                with open (soc_summary_path ,'w',newline ='',encoding ='utf-8')as csvfile :
                    writer =csv .writer (csvfile )
                    writer .writerow ([
                    'episode',
                    'arrival_mean',
                    'arrival_max',
                    'arrival_min',
                    'arrival_std',
                    'needed_mean',
                    'needed_max',
                    'needed_min',
                    'needed_std',
                    'dwell_hours_mean',
                    'dwell_hours_max',
                    'dwell_hours_min',
                    'dwell_hours_std',
                    'num_records',
                    ])
                    for stat in episode_soc_stats :
                        writer .writerow ([
                        stat ['episode'],
                        f"{stat['arrival_mean']:.4f}",
                        f"{stat['arrival_max']:.4f}",
                        f"{stat['arrival_min']:.4f}",
                        f"{stat['arrival_std']:.4f}",
                        f"{stat['needed_mean']:.4f}",
                        f"{stat['needed_max']:.4f}",
                        f"{stat['needed_min']:.4f}",
                        f"{stat['needed_std']:.4f}",
                        f"{stat['dwell_mean']:.4f}",
                        f"{stat['dwell_max']:.4f}",
                        f"{stat['dwell_min']:.4f}",
                        f"{stat['dwell_std']:.4f}",
                        stat ['count'],
                        ])

            except Exception as csv_error :
                warnings .warn (f"Failed to write episode SoC summary CSV: {csv_error}")



        try :
            import numpy as _np
            if test_results ['all_local_rewards']:
                avg_local =float (_np .mean (test_results ['all_local_rewards']))
            else :
                avg_local =0.0
            if test_results ['all_global_rewards']:
                avg_global =float (_np .mean (test_results ['all_global_rewards']))
            else :
                avg_global =0.0

            pm =test_results ['performance_metrics']
            avg_pm ={
            'soc_miss_count':[float (_np .mean (pm ['soc_miss_count']))]if pm .get ('soc_miss_count')else [],
            'central_soc_miss_count':[float (_np .mean (pm ['central_soc_miss_count']))]if pm .get ('central_soc_miss_count')else [],
            'central_avg_soc_deficit':[float (_np .mean (pm ['central_avg_soc_deficit']))]if pm .get ('central_avg_soc_deficit')else [],
            'surplus_absorption_rate':[float (_np .mean (pm ['surplus_absorption_rate']))]if pm .get ('surplus_absorption_rate')else [],
            'supply_cooperation_rate':[float (_np .mean (pm ['supply_cooperation_rate']))]if pm .get ('supply_cooperation_rate')else [],
            'departing_evs':[int (_np .sum (pm ['departing_evs']))]if pm .get ('departing_evs')else [],
            'departing_evs_soc_met':[int (_np .sum (pm ['departing_evs_soc_met']))]if pm .get ('departing_evs_soc_met')else [],
            'central_departing_evs_soc_met':[int (_np .sum (pm ['central_departing_evs_soc_met']))]if pm .get ('central_departing_evs_soc_met')else [],
            'surplus_steps':[int (_np .sum (pm ['surplus_steps']))]if pm .get ('surplus_steps')else [],
            'surplus_within_narrow':[int (_np .sum (pm ['surplus_within_narrow']))]if pm .get ('surplus_within_narrow')else [],
            'shortage_steps':[int (_np .sum (pm ['shortage_steps']))]if pm .get ('shortage_steps')else [],
            'shortage_within_narrow':[int (_np .sum (pm ['shortage_within_narrow']))]if pm .get ('shortage_within_narrow')else [],
            'zero_request_steps':[int (_np .sum (pm ['zero_request_steps']))]if pm .get ('zero_request_steps')else [],
            'zero_request_within_narrow':[int (_np .sum (pm ['zero_request_within_narrow']))]if pm .get ('zero_request_within_narrow')else [],
            'system_surplus_steps':[int (_np .sum (pm ['system_surplus_steps']))]if pm .get ('system_surplus_steps')else [],
            'system_surplus_within_narrow':[int (_np .sum (pm ['system_surplus_within_narrow']))]if pm .get ('system_surplus_within_narrow')else [],
            'system_shortage_steps':[int (_np .sum (pm ['system_shortage_steps']))]if pm .get ('system_shortage_steps')else [],
            'system_shortage_within_narrow':[int (_np .sum (pm ['system_shortage_within_narrow']))]if pm .get ('system_shortage_within_narrow')else [],
            'system_zero_request_steps':[int (_np .sum (pm ['system_zero_request_steps']))]if pm .get ('system_zero_request_steps')else [],
            'system_zero_request_within_narrow':[int (_np .sum (pm ['system_zero_request_within_narrow']))]if pm .get ('system_zero_request_within_narrow')else [],
            'central_surplus_steps':[int (_np .sum (pm ['central_surplus_steps']))]if pm .get ('central_surplus_steps')else [],
            'central_surplus_within_narrow':[int (_np .sum (pm ['central_surplus_within_narrow']))]if pm .get ('central_surplus_within_narrow')else [],
            'central_shortage_steps':[int (_np .sum (pm ['central_shortage_steps']))]if pm .get ('central_shortage_steps')else [],
            'central_shortage_within_narrow':[int (_np .sum (pm ['central_shortage_within_narrow']))]if pm .get ('central_shortage_within_narrow')else [],
            'central_zero_request_steps':[int (_np .sum (pm ['central_zero_request_steps']))]if pm .get ('central_zero_request_steps')else [],
            'central_zero_request_within_narrow':[int (_np .sum (pm ['central_zero_request_within_narrow']))]if pm .get ('central_zero_request_within_narrow')else [],
            'raw_actor_mae_kw':[float (_np .mean (pm ['raw_actor_mae_kw']))]if pm .get ('raw_actor_mae_kw')else [],
            'central_corrected_ev_steps':[int (_np .sum (pm ['central_corrected_ev_steps']))]if pm .get ('central_corrected_ev_steps')else [],
            'central_corrected_station_steps':[int (_np .sum (pm ['central_corrected_station_steps']))]if pm .get ('central_corrected_station_steps')else [],
            'central_correction_active_steps':[int (_np .sum (pm ['central_correction_active_steps']))]if pm .get ('central_correction_active_steps')else [],
            'central_absolute_correction_kwh':[float (_np .mean (pm ['central_absolute_correction_kwh']))]if pm .get ('central_absolute_correction_kwh')else [],
            'central_max_abs_aggregate_correction_kw':[float (_np .max (pm ['central_max_abs_aggregate_correction_kw']))]if pm .get ('central_max_abs_aggregate_correction_kw')else [],
            'central_max_corrected_evs_per_step':[int (_np .max (pm ['central_max_corrected_evs_per_step']))]if pm .get ('central_max_corrected_evs_per_step')else [],
            'central_max_corrected_stations_per_step':[int (_np .max (pm ['central_max_corrected_stations_per_step']))]if pm .get ('central_max_corrected_stations_per_step')else [],
            'central_max_station_target_error_kw':[float (_np .max (pm ['central_max_station_target_error_kw']))]if pm .get ('central_max_station_target_error_kw')else [],
            'pre_bess_mae_kw':[float (_np .mean (pm ['pre_bess_mae_kw']))]if pm .get ('pre_bess_mae_kw')else [],
            'post_bess_mae_kw':[float (_np .mean (pm ['post_bess_mae_kw']))]if pm .get ('post_bess_mae_kw')else [],
            'bess_final_soc_pct':[float (_np .mean (pm ['bess_final_soc_pct']))]if pm .get ('bess_final_soc_pct')else [],
            'bess_throughput_kwh':[float (_np .mean (pm ['bess_throughput_kwh']))]if pm .get ('bess_throughput_kwh')else [],
            'bess_power_limit_hits':[int (_np .sum (pm ['bess_power_limit_hits']))]if pm .get ('bess_power_limit_hits')else [],
            'bess_energy_limit_hits':[int (_np .sum (pm ['bess_energy_limit_hits']))]if pm .get ('bess_energy_limit_hits')else [],
            'bess_max_abs_power_kw':[float (_np .max (pm ['bess_max_abs_power_kw']))]if pm .get ('bess_max_abs_power_kw')else [],
            }
            if enable_switch_metrics :
                avg_pm ['avg_switches']=[float (_np .mean (pm ['avg_switches']))]if pm .get ('avg_switches')else []
            if enable_stlimit_metrics :
                avg_pm ['station_limit_hits']=[int (_np .sum (pm ['station_limit_hits']))]if pm .get ('station_limit_hits')else []
                avg_pm ['station_limit_steps']=[int (_np .sum (pm ['station_limit_steps']))]if pm .get ('station_limit_steps')else []
                avg_pm ['station_charge_limit_hits']=[int (_np .sum (pm ['station_charge_limit_hits']))]if pm .get ('station_charge_limit_hits')else []
                avg_pm ['station_discharge_limit_hits']=[int (_np .sum (pm ['station_discharge_limit_hits']))]if pm .get ('station_discharge_limit_hits')else []
                avg_pm ['station_limit_penalty_total']=[float (_np .sum (pm ['station_limit_penalty_total']))]if pm .get ('station_limit_penalty_total')else []
        except Exception as exc :
            warnings .warn (f"Failed to aggregate test performance metrics: {exc}")
            avg_local =avg_global =0.0
            avg_pm ={'soc_miss_count':[],'surplus_absorption_rate':[],'supply_cooperation_rate':[]}


        skip_history_png_flag =bool (not enable_history_png )
        # A PNG that cannot be written must not end the run. These two write to
        # fixed filenames that are overwritten every interim test, so anything
        # holding one open -- a viewer, the indexer -- makes the write fail for
        # that moment only. The detail plots below were already guarded; these
        # were not, and a transient lock on test_performance_metrics.png killed
        # a run twice at the 100-episode plot interval. The CSV history is
        # written before this point, so a skipped PNG loses nothing but the
        # picture, and the next interim test redraws it.
        try :
            plot_daily_rewards ([avg_local ],[avg_global ],
            results_dir ,episode_num =1 ,
            performance_metrics =avg_pm ,title_prefix ="Test Results",
            skip_png =skip_history_png_flag )
        except Exception as _e :
            warnings .warn (f"Failed to plot daily rewards: {_e}")

        try :
            plot_performance_metrics (avg_pm ,results_dir ,title_prefix ="Test Results",
            skip_png =skip_history_png_flag )
        except Exception as _e :
            warnings .warn (f"Failed to plot performance metrics: {_e}")

        skip_detail_png_flag =bool (not enable_png )
        if (not skip_detail_png_flag )and save_test_detail_files :
            latest_episodes =test_results .get ('all_episode_data',{})or {}
            if latest_episodes :
                try :
                    plot_station_cooperation_full (latest_episodes ,results_dir ,random_window =random_window ,title_prefix ="Test Results")
                except Exception as _e :
                    warnings .warn (f"Failed to plot station cooperation: {_e}")
                try :
                    plot_ev_detailed_soc (latest_episodes ,results_dir ,display_steps =10 ,random_window =random_window ,title_prefix ="Test Results")
                except Exception as _e :
                    warnings .warn (f"Failed to plot EV SoC detail: {_e}")


            for _name ,_fn in (
            ("power mismatch",plot_power_mismatch_analysis ),
            ("reward breakdown",plot_reward_breakdown ),
            ("arrival counts",plot_arrival_counts ),
            ):
                try :
                    _fn (latest_episodes ,results_dir ,title_prefix ="Test Results")
                except Exception as _e :
                    warnings .warn (f"Failed to plot {_name}: {_e}")
        elif skip_detail_png_flag and save_test_detail_files and verbose :
            print ("[Info] Detailed test plots are skipped. Basic metrics are saved in CSV.")





        if not bool (update_history ):
            if bool (print_summary ):
                try :
                    _print_test_summary (test_results ,test_episode_num =test_episode_num ,
                    duration_sec =time .time ()-test_begin_time )
                except Exception as exc :
                    warnings .warn (f"Failed to print test summary: {exc}")
            try :
                agent .set_test_mode (False )
            finally :
                if original_use_tensorboard is not None :
                    agent .use_tensorboard =original_use_tensorboard
                _restore_rng_state (rng_state )
            return test_results

        try :
            base_results_dir =os .path .dirname (results_dir )if "TEST"in os .path .basename (results_dir )else results_dir
            os .makedirs (base_results_dir ,exist_ok =True )

            history_path =os .path .join (base_results_dir ,'test_history.json')

            if os .path .exists (history_path ):
                with open (history_path ,'r',encoding ='utf-8')as f :
                    hist =json .load (f )
            else :
                hist ={
                'episodes':[],
                'local_rewards':[],
                'global_rewards':[],
                'soc_miss_count':[],
                'avg_soc_deficit':[],
                'surplus_absorption_rate':[],
                'supply_cooperation_rate':[],
                'departing_evs':[],
                'departing_evs_soc_met':[],
                'surplus_steps':[],
                'surplus_within_narrow':[],
                'shortage_steps':[],
                'shortage_within_narrow':[],
                'zero_request_steps':[],
                'zero_request_within_narrow':[],
                }
                if enable_switch_metrics :
                    hist ['avg_switches']=[]
                if enable_stlimit_metrics :
                    hist ['station_limit_hits']=[]
                    hist ['station_limit_steps']=[]
                    hist ['station_charge_limit_hits']=[]
                    hist ['station_discharge_limit_hits']=[]
                    hist ['station_limit_penalty_total']=[]


            try :
                import numpy as _np
                cur_local =float (_np .mean (test_results ['all_local_rewards']))if test_results .get ('all_local_rewards')else 0.0
                cur_global =float (_np .mean (test_results ['all_global_rewards']))if test_results .get ('all_global_rewards')else 0.0
                pm =test_results .get ('performance_metrics',{})
                cur_soc_miss =float (_np .mean (pm .get ('soc_miss_count',[])))if pm .get ('soc_miss_count')else 0.0
                cur_avg_soc_deficit =float (_np .mean (pm .get ('avg_soc_deficit',[])))if pm .get ('avg_soc_deficit')else 0.0
                cur_surplus_rate =float (_np .mean (pm .get ('surplus_absorption_rate',[])))if pm .get ('surplus_absorption_rate')else 0.0
                cur_supply_rate =float (_np .mean (pm .get ('supply_cooperation_rate',[])))if pm .get ('supply_cooperation_rate')else 0.0


                cur_departing_evs =int (_np .sum (pm .get ('departing_evs',[])))
                cur_departing_evs_soc_met =int (_np .sum (pm .get ('departing_evs_soc_met',[])))
                cur_surplus_steps =int (_np .sum (pm .get ('surplus_steps',[])))
                cur_surplus_within =int (_np .sum (pm .get ('surplus_within_narrow',[])))
                cur_shortage_steps =int (_np .sum (pm .get ('shortage_steps',[])))
                cur_shortage_within =int (_np .sum (pm .get ('shortage_within_narrow',[])))
                cur_zero_steps =int (_np .sum (pm .get ('zero_request_steps',[])))
                cur_zero_within =int (_np .sum (pm .get ('zero_request_within_narrow',[])))
                cur_station_limit_hits =int (_np .sum (pm .get ('station_limit_hits',[])))
                cur_station_limit_steps =int (_np .sum (pm .get ('station_limit_steps',[])))
                cur_station_charge_limit_hits =int (_np .sum (pm .get ('station_charge_limit_hits',[])))
                cur_station_discharge_limit_hits =int (_np .sum (pm .get ('station_discharge_limit_hits',[])))
                cur_station_limit_penalty_total =float (_np .sum (pm .get ('station_limit_penalty_total',[])))
                # Tracking error of each checkpoint, kept with the rates so the
                # controller error can be read back from the history.
                cur_errors ={
                key :(float (_np .mean (pm [key ]))if pm .get (key )else float ('nan'))
                for key in _HISTORY_ERROR_KEYS
                }
            except Exception as exc :
                warnings .warn (f"Failed to aggregate current test history metrics: {exc}")
                cur_local =cur_global =cur_soc_miss =cur_avg_soc_deficit =cur_surplus_rate =cur_supply_rate =0.0
                cur_departing_evs =cur_departing_evs_soc_met =0
                cur_surplus_steps =cur_surplus_within =cur_shortage_steps =cur_shortage_within =0
                cur_zero_steps =cur_zero_within =None
                cur_station_limit_hits =cur_station_limit_steps =0
                cur_station_charge_limit_hits =cur_station_discharge_limit_hits =0
                cur_station_limit_penalty_total =0.0
                cur_errors ={key :float ('nan')for key in _HISTORY_ERROR_KEYS }


            for key in _HISTORY_ERROR_KEYS :
                hist .setdefault (key ,[float ('nan')]*len (hist ['episodes']))
            # Histories written before the no-instruction counts were stored
            # have none for their earlier checkpoints; null keeps those rows
            # from being read as zero no-instruction steps.
            for key in ('zero_request_steps','zero_request_within_narrow'):
                hist .setdefault (key ,[None ]*len (hist ['episodes']))
            if test_episode_num in hist ['episodes']:
                idx =hist ['episodes'].index (test_episode_num )
                hist ['local_rewards'][idx ]=cur_local
                hist ['global_rewards'][idx ]=cur_global
                hist ['soc_miss_count'][idx ]=cur_soc_miss
                hist ['avg_soc_deficit'][idx ]=cur_avg_soc_deficit
                hist ['surplus_absorption_rate'][idx ]=cur_surplus_rate
                hist ['supply_cooperation_rate'][idx ]=cur_supply_rate
                hist .setdefault ('departing_evs',[0 ]*len (hist ['episodes']))[idx ]=cur_departing_evs
                hist .setdefault ('departing_evs_soc_met',[0 ]*len (hist ['episodes']))[idx ]=cur_departing_evs_soc_met
                hist ['surplus_steps'][idx ]=cur_surplus_steps
                hist ['surplus_within_narrow'][idx ]=cur_surplus_within
                hist ['shortage_steps'][idx ]=cur_shortage_steps
                hist ['shortage_within_narrow'][idx ]=cur_shortage_within
                hist ['zero_request_steps'][idx ]=cur_zero_steps
                hist ['zero_request_within_narrow'][idx ]=cur_zero_within
                for key in _HISTORY_ERROR_KEYS :
                    hist [key ][idx ]=cur_errors [key ]
                if enable_switch_metrics :
                    hist .setdefault ('avg_switches',[0.0 ]*len (hist ['episodes']))[idx ]=float (_np .mean (pm ['avg_switches']))if pm .get ('avg_switches')else 0.0
                if enable_stlimit_metrics :
                    hist .setdefault ('station_limit_hits',[0 ]*len (hist ['episodes']))[idx ]=cur_station_limit_hits
                    hist .setdefault ('station_limit_steps',[0 ]*len (hist ['episodes']))[idx ]=cur_station_limit_steps
                    hist .setdefault ('station_charge_limit_hits',[0 ]*len (hist ['episodes']))[idx ]=cur_station_charge_limit_hits
                    hist .setdefault ('station_discharge_limit_hits',[0 ]*len (hist ['episodes']))[idx ]=cur_station_discharge_limit_hits
                    hist .setdefault ('station_limit_penalty_total',[0.0 ]*len (hist ['episodes']))[idx ]=cur_station_limit_penalty_total
            else :
                hist ['episodes'].append (test_episode_num )
                hist ['local_rewards'].append (cur_local )
                hist ['global_rewards'].append (cur_global )
                hist ['soc_miss_count'].append (cur_soc_miss )
                hist ['avg_soc_deficit'].append (cur_avg_soc_deficit )
                hist ['surplus_absorption_rate'].append (cur_surplus_rate )
                hist ['supply_cooperation_rate'].append (cur_supply_rate )
                hist .setdefault ('departing_evs',[]).append (cur_departing_evs )
                hist .setdefault ('departing_evs_soc_met',[]).append (cur_departing_evs_soc_met )
                hist ['surplus_steps'].append (cur_surplus_steps )
                hist ['surplus_within_narrow'].append (cur_surplus_within )
                hist ['shortage_steps'].append (cur_shortage_steps )
                hist ['shortage_within_narrow'].append (cur_shortage_within )
                hist ['zero_request_steps'].append (cur_zero_steps )
                hist ['zero_request_within_narrow'].append (cur_zero_within )
                for key in _HISTORY_ERROR_KEYS :
                    hist [key ].append (cur_errors [key ])
                if enable_switch_metrics :
                    hist .setdefault ('avg_switches',[]).append (float (_np .mean (pm ['avg_switches']))if pm .get ('avg_switches')else 0.0 )
                if enable_stlimit_metrics :
                    hist .setdefault ('station_limit_hits',[]).append (cur_station_limit_hits )
                    hist .setdefault ('station_limit_steps',[]).append (cur_station_limit_steps )
                    hist .setdefault ('station_charge_limit_hits',[]).append (cur_station_charge_limit_hits )
                    hist .setdefault ('station_discharge_limit_hits',[]).append (cur_station_discharge_limit_hits )
                    hist .setdefault ('station_limit_penalty_total',[]).append (cur_station_limit_penalty_total )


            if hist ['episodes']:
                order =sorted (range (len (hist ['episodes'])),key =lambda i :hist ['episodes'][i ])
                hist ={
                'episodes':[hist ['episodes'][i ]for i in order ],
                'local_rewards':[hist ['local_rewards'][i ]for i in order ],
                'global_rewards':[hist ['global_rewards'][i ]for i in order ],
                'soc_miss_count':[hist ['soc_miss_count'][i ]for i in order ],
                'avg_soc_deficit':[hist .get ('avg_soc_deficit',[0.0 ]*len (order ))[i ]for i in order ],
                'surplus_absorption_rate':[hist ['surplus_absorption_rate'][i ]for i in order ],
                'supply_cooperation_rate':[hist ['supply_cooperation_rate'][i ]for i in order ],
                'departing_evs':[hist .get ('departing_evs',[0 ]*len (order ))[i ]for i in order ],
                'departing_evs_soc_met':[hist .get ('departing_evs_soc_met',[0 ]*len (order ))[i ]for i in order ],
                'surplus_steps':[hist .get ('surplus_steps',[0 ]*len (order ))[i ]for i in order ],
                'surplus_within_narrow':[hist .get ('surplus_within_narrow',[0 ]*len (order ))[i ]for i in order ],
                'shortage_steps':[hist .get ('shortage_steps',[0 ]*len (order ))[i ]for i in order ],
                'shortage_within_narrow':[hist .get ('shortage_within_narrow',[0 ]*len (order ))[i ]for i in order ],
                'zero_request_steps':[hist ['zero_request_steps'][i ]for i in order ],
                'zero_request_within_narrow':[hist ['zero_request_within_narrow'][i ]for i in order ],
                **{
                key :[hist .get (key ,[float ('nan')]*len (order ))[i ]for i in order ]
                for key in _HISTORY_ERROR_KEYS
                },
                }
                if enable_switch_metrics :
                    hist ['avg_switches']=[hist .get ('avg_switches',[0.0 ]*len (order ))[i ]for i in order ]


            with open (history_path ,'w',encoding ='utf-8')as f :
                json .dump (hist ,f ,ensure_ascii =False ,indent =2 )


            # Keep root-level history plots in sync with the CSV history.
            skip_history_png_flag =bool (not enable_history_png )

            plot_daily_rewards (hist ['local_rewards'],hist ['global_rewards'],base_results_dir ,
            title_prefix ="Test Results",skip_png =skip_history_png_flag ,
            x_values =hist ['episodes'])

            perf_hist ={
            'soc_miss_count':hist ['soc_miss_count'],
            'avg_soc_deficit':hist .get ('avg_soc_deficit',[]),
            'surplus_absorption_rate':hist ['surplus_absorption_rate'],
            'supply_cooperation_rate':hist ['supply_cooperation_rate'],
            'departing_evs':hist .get ('departing_evs',[]),
            'departing_evs_soc_met':hist .get ('departing_evs_soc_met',[]),
            'surplus_steps':hist .get ('surplus_steps',[]),
            'surplus_within_narrow':hist .get ('surplus_within_narrow',[]),
            'shortage_steps':hist .get ('shortage_steps',[]),
            'shortage_within_narrow':hist .get ('shortage_within_narrow',[]),
            'zero_request_steps':hist .get ('zero_request_steps',[]),
            'zero_request_within_narrow':hist .get ('zero_request_within_narrow',[]),
            **{key :hist .get (key ,[])for key in _HISTORY_ERROR_KEYS },
            }
            if enable_switch_metrics :
                perf_hist ['avg_switches']=hist .get ('avg_switches',[])
            plot_performance_metrics (perf_hist ,base_results_dir ,title_prefix ="Test Results",
            x_values =hist ['episodes'],skip_png =skip_history_png_flag )
        except Exception as e :
            warnings .warn (f"Failed to update test history artifacts: {e}")

        if bool (print_summary ):
            try :
                _print_test_summary (test_results ,test_episode_num =test_episode_num ,
                duration_sec =time .time ()-test_begin_time )
            except Exception as exc :
                warnings .warn (f"Failed to print test summary: {exc}")


        try :
            agent .set_test_mode (False )
        finally :
            if original_use_tensorboard is not None :
                agent .use_tensorboard =original_use_tensorboard
            _restore_rng_state (rng_state )
        return test_results
